# 2026-01-25 10:45
# act-android.yml
name: act - Android CI

on:
#  pull_request:
#    paths-ignore:
#      - '.idea/**'
#      - '.gitattributes'
#      - '.github/**.json'
#      - '.gitignore'
#      - '.gitmodules'
#      - '**.md'
#      - 'LICENSE'
#      - 'NOTICE'
  workflow_dispatch:

env:
  PRG_NAME: "weather-notification"
  PRG_VERSION: "v0.3.15"
  TAG_NAME: "weather-notification"
  TAG_VERSION: "v0.3.15"
  TAG_BUILD: "-b"
  TAG_REF: "0000000"
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  #  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #  alias: ${{ secrets.ANDROID_ALIAS }}
  #  keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
  #  keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}  

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: deep-soft/checkout@v4
      - uses: deep-soft/wrapper-validation-action@v2

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: deep-soft/checkout@v4

      - name: Get ref, set build version
        continue-on-error: true
        shell: bash
        run: |
          _ref_all_=$(git log -1 --format='%H');
          # _ref_=$(echo ${_ref_all_::7});
          _ref_org_=${{ env.TAG_REF }};
          _ref_len_="${#_ref_org_}";
          _ref_=$(echo ${_ref_all_::$_ref_len_});
          # _prg_version_=$(grep "versionName " core/build.gradle | awk -F ' ' '{print $2}' | awk -F '"' '{print $2}');
          # echo "TAG_REF=$_ref_" >> $GITHUB_ENV;
          _prg_version_=$(grep "versionName " core/build.gradle | awk -F ' ' '{print $2}');
          echo "TAG_REF=v$_ref_" >> $GITHUB_ENV;
          _build_=${{ env.TAG_BUILD }}.$_ref_;
          echo "TAG_BUILD=$_build_";
          echo "PRG_VERSION=$_prg_version_";
          echo "TAG_VERSION=$_prg_version_";
          echo "TAG_BUILD=$_build_" >> $GITHUB_ENV;
          echo "PRG_VERSION=$_prg_version_" >> $GITHUB_ENV;
          echo "TAG_VERSION=$_prg_version_" >> $GITHUB_ENV;

      - name: Print ref, build version
        shell: bash
        run: |
          echo "VER: ${{ env.PRG_VERSION }};
          echo "TAG: ${{ env.TAG_VERSION }};
          echo "REF: ${{ env.TAG_REF }};
          echo "BLD: ${{ env.TAG_BUILD }};
          echo "${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}-${{ env.TAG_BUILD }}" > _tag_name_.txt;
          echo "${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}-${{ env.TAG_BUILD }}" > ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.txt;

      - name: Create source archive
        continue-on-error: true
        uses: deep-soft/zip-release@v2.2
        with:
          type: 'tar.xz'
          filename: "${{ env.PRG_NAME }}-src-${{ env.PRG_VERSION }}-${{ env.TAG_BUILD }}"
          directory: '.'
          exclusions: ''
          recursive_exclusions: ''
          ignore_git: 'no'
          path: '.'
          env_variable: ASSET_SRC
        # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Publish src archive
        continue-on-error: true
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{ env.ASSET_SRC }}

      - name: Setup java v4
        uses: deep-soft/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

#      - name: Gradle Build v3
#        uses: gradle/gradle-build-action@v3

      - name: Gradle Build v4
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      # - run: ./gradlew assembleDebug detekt spotlessCheck testsOnCi
      - name: gradlew assembleRelease
        run: |
          chmod +x ./gradlew;
          ./gradlew assembleRelease;

      - name: Upload Artifact
        uses: deep-soft/upload-artifact@v4
        with:
          name: upload-artifact
          path: |
            ./app-${{ env.PRG_NAME }}/build/outputs/apk/

# full begin
      - name: Copy apk from outputs/
        shell: bash
        run: |
          set -x;
          mkdir -p signed-apk;
          echo "LIST: " ./core/build/outputs/apk/release/;
          ls -l ./core/build/outputs/apk/release/;
          cp ./core/build/outputs/apk/release/core-release-unsigned.apk ./signed-apk/ || true;
          echo "LIST: " ./signed-apk/;
          ls -l ./signed-apk/;

          mv ./signed-apk/core-release-unsigned.apk ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk;
          echo "LIST: " ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk;
          ls -l ./signed-apk/;

      - uses: deep-soft/sign-android-release@v1
        name: Sign app APK
        if: env.ANDROID_SIGNING_KEY != null
        id: sign-android
        with:
          releaseDirectory: ./signed-apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Artifacts
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/upload-artifact@v4
        with:
          name: ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.apk
          path: ${{steps.sign-android.outputs.signedReleaseFile}}

      - name: Publish signed apk package
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ${{steps.sign-android.outputs.signedReleaseFile}}
            ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.txt
            _tag_name_.txt

      - name: Publish version build - signed apk package
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{steps.sign-android.outputs.signedReleaseFile}}
            ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.txt
            _tag_name_.txt

      - name: Publish unsigned apk package
        if: env.ANDROID_SIGNING_KEY == null
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-unsigned.apk
            _tag_name_.txt
# full end
